# -*- coding: utf-8 -*-
"""StudentData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_t2TYIv4NumeAfakd_fn0uGtGjosh_iS
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

uploaded

import io

df = pd.read_csv(io.StringIO(uploaded['student-mat.csv'].decode('utf-8')), sep=";")

df.head()

import numpy as np
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle
import matplotlib.pyplot as pyplot
import pickle
from matplotlib import style

df = df[["G1", "G2","G3", "studytime", "failures", "absences"]]

df.head()

predict = "G3"

x = np.array(df.drop([predict], 1))
y = np.array(df[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.1)

best = 0
for _ in range(30):
  x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.1)

  linear = linear_model.LinearRegression()

  linear.fit(x_train, y_train)
  acc = linear.score(x_test, y_test)
  print(acc)
  
  if acc > best:
    best = acc
    with open("studentmodel.pickle", "wb") as f:
      pickle.dump(linear, f)

pickle_in = open("studentmodel.pickle", "rb")

linear = pickle.load(pickle_in)

print("Co: ", linear.coef_)
print("Intercept: ", linear.intercept_)

predictions = linear.predict(x_test)

for x in range(len(predictions)):
  print(predictions[x], x_test[x], y_test[x])

p = "absences"
style.use("ggplot")
pyplot.scatter(df[p], df[predict])
pyplot.xlabel(p)
pyplot.ylabel("G3")
pyplot.show